# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Helly Gohil
title: Bachelor of Computer Engineering
email: hellygohil43559@gmail.com
# website: badamnshake.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
# github_username: badamnshake
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: badamnshake
# linkedin_username: kartavya-gohil-b25945210
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
#about_title: About Me
about_content: | # this will include new lines to allow paragraphs
  Hi, My name is Helly Gohil, I am currently pursuing an Bachelor
  of Engineering at GEC Gandlhinagar. I have made a few projects
  in React. I have also wasted few weeks tinkering my Linux
  Distro. I am most skilled in: <mark> Javascript </mark>
  <mark> Java </mark> and <mark> React </mark>

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Cyber safety and security awareness workshop
        # sub_title: Cyber safety and security awareness workshop
        caption: Sept 2019
        description: | # this will include new lines to allow paragraphs
          Learned about Cyber Security and many other topics related to
          it. Researched and made a presentation about cyber security. I
          gave talks to students on various level in many schools.
      - layout: left
        title: Summer Internship at INFOLABZ IT SERVICE PVT.LTD
        # sub_title: Cyber safety and security awareness workshop
        caption: June 2022
        description: | # this will include new lines to allow paragraphs
          Worked with Pre-made API's to create dynamic web pages. mostly
          using Vanilla javascript and html and css. Also used modern
          syntax and fetch API to get the data and display
        # I worked with .Net and Angular with microservices architecture and with SQL Databases. Learned about various design patterns in backend and clean architecture. Currently working in live project.
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Movie Seat Booking
        # link: github.com/badamnshake/jobportal
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          React Css and UI Design
        description: | # this will include new lines to allow paragraphs
          A project made to make booking seats for a movie theater
          effectively with a modern UI, Where you can select which movie
          seats you would book with mind in screen of theater. It uses
          Click events and local store to do interactivity.
        # A project made with microservice architecture (with api gateway and seperation of databases) in the backend. The project has two roles for users. Employers can create vacancies and Job seekers can apply to the posted jobs, I also leveraged stored procedures in SQL server. various features include authentication, RBAC and modern architecture.
      - layout: top-middle
        title: Dad Jokes Project
        # link: github.com/badamnshake/SpaceTrashCleaner
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          React, Html, Vanilla JS
        description: | # this will include new lines to allow paragraphs
          The User clicks to generate the jokes and as they make and break
          changes, the system responds with some emojis depending on their
          jokes.
      - layout: top-middle
        title: Apna-Cart
        # link: github.com/badamnshake/RPGAdventure3D
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          An E-commerce Interactive Cart (made with React)
        description: | # this will include new lines to allow paragraphs
          Many Sites today sell products or merch to get extra income, and
          Cart and checkout pages are everywhere so It was a case study to
          make users ease with cart. Items Get changed and total gets
          recalculated when user interacts with items in cart.
        # It started with obsession with RPG games. I used Unity and C# to create the game. It is a 3D game where the player can move around and interact with the environment. I also used shaders, cinemachine and designed the game with 3d assets. The game has enemy ai and a huge combat and inventory system
  - title: Education # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      <mark>Government engineering college,Gandhinagar</mark> ->> 2023 
      - Computer Engineering, with 8.52 CGPA 

      <mark>HSC</mark> ->> 2019 
      - I completed HSC (10+2) in Science with 75%. 

      <mark>SSC</mark> ->> 2017
      - I completed my SSC with 87%.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in game programming and software engineering some of my other interests and hobbies are:
      - [Reading (pirated ebooks!)](https://www.youtube.com/watch?v=LZgeIReY04c), [Gaming](https://youtu.be/hIRtSMToM6s), [Garba](https://www.youtube.com/watch?v=XLj9QtidiTo), [Dancing!!!](https://youtu.be/6Ron-Ikenfc)

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
