# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Kartavya Gohil
title: Undergrad student
email: kargo.tavhilya@protonmail.com
website: badamnshake.github.io

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username: badamnshake
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: badamnshake
#linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
#about_title: About Me
about_content: | # this will include new lines to allow paragraphs
  Hi, My name is Kartavya Gohil, I am currently pursuing an Internship at Synoptek. I have made a few Games in Unity. I have also wasted few weeks tinkering my Linux Distro.
  I have worked with .Net Microservices, Angular in current internship, and also React and Nodejs (did some freelance projects).
  I am most skilled in: <mark> Unity Game Engine </mark> <mark> Shaders </mark> and <mark>Game Physics</mark>

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Adventurer's Treasure
        link: github.com/badamnshake/RPGAdventure3D
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A RPG set in a Sci-fi-ish fantasy land

        description: | # this will include new lines to allow paragraphs
          A game with an uplifting environment. I started this after dibbling around in 3D world of games, It began with an obsession with RPG’s and learning about game design, lighting, and by implementing shaders I improved frame rates by 30%.
      - layout: top-middle
        title: SpaceTrashCleaner
        link: github.com/badamnshake/SpaceTrashCleaner
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A simple beat the highscore 2D game
        description: | # this will include new lines to allow paragraphs
          I started this project mainly to learn about vector math and explore more in 2D and shaders, I have learned how to make particle systems along the way and implemented a lot of math.
      - layout: top-middle
        title: MiniArena
        link: github.com/badamnshake/Mini-Arena
        # link_text: Project Website
        #additional_links:
        #  - title:  sproogen/modern-resume-theme
        #    icon: fab fa-github
        #    url: github.com/sproogen/modern-resume-theme
        # - title:  Github page for project (eg. sproogen/modern-resume-theme)
        #   icon: fab fa-github
        #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          A Brawl Multiplayer Game
        description: | # this will include new lines to allow paragraphs
          I wanted to learn the ins and outs of Multiplayer, so I started this project, I am still in the process of making it.
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Synoptek
        sub_title: Intern (Fullstack .Net and Microservices)
        caption: January 2022 - present)
        description: | # this will include new lines to allow paragraphs
          I worked with Dotnet and Angular with Microservices Architecture and with SQL Databases
  - title: Education # Title for the section
    layout: text
    content: | # this will include new lines to allow paragraphs
      <mark>L.J. Institute Of Engineering And Technology</mark> ->> 2022 
      - Currently studying in LJIET Computer Science, (current CGPA=9.57)

      <mark>Swami Vivekananda School</mark> ->> 2018 
      - I completed HSC (10+2) in Science with 75% and a rank of 5850 in gshseb. 

      <mark>Savoday Vidhyamandir</mark> ->> 2016
      - I completed my SSC with 87%.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in game programming and software engineering some of my other interests and hobbies are:
      - [Reading (pirated ebooks!)](https://www.youtube.com/watch?v=LZgeIReY04c)
      - [Gaming](https://youtu.be/hIRtSMToM6s)
      - [Linguistics  currently at N5 in japanese](https://www.youtube.com/watch?v=XLj9QtidiTo)
      - [Becoming a Spider](https://youtu.be/6Ron-Ikenfc)

# Footer
#footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
